// Package wgtun parses the fake-TUN ping packets the in-memory WireGuard
// tests exchange, so the server's echo responder can tell an echo ping from
// anything else on the tunnel.
package wgtun

import (
	"net/netip"
)

// PingSrc extracts the source address from a ping packet produced by
// tuntest.Ping. ok is false if the packet is not a parseable echo ping.
//
// Layout (tuntest.genICMPv4): [ipv4:20][icmp:8][icmp payload:4]. The IPv4
// source address sits at bytes 12-15 and the ICMP type (8=echo) at byte 20.
// The IPv4 header is assumed to be exactly 20 bytes (IHL 5, no options):
// that holds because every ping in the harness is generated by tuntest.Ping
// on both ends, which hardcodes a 20-byte header. A foreign packet with
// IPv4 options would misparse, but none of those ever reach the fake TUN.
func PingSrc(msg []byte) (netip.Addr, bool) {
	if len(msg) < 28 || msg[20] != 8 {
		return netip.Addr{}, false
	}
	src := netip.AddrFrom4([4]byte{msg[12], msg[13], msg[14], msg[15]})
	return src, src.IsValid()
}
